### ISSUE TITLE
Add attribute: data, possible?

### ISSUE THREAD

**Issue by vhugogarcia** [vdw/HideSeek#15]
Hello,

Is is possible to set the attribute:'data' and it searches for those attributes in the listing?
Since data- is now used to store information.

Note: I added it, but it seems not to work.

Any workaround?

thank you.

**Comment by vdw** [comment]
Hi, you **can** search against **any** attribute of your list elements.
For data attributes, set to the option "attribute" the "data-attribute-name". E.g.:

    $('#search').hideseek({
        attribute: 'data-name'
    });

[Here](http://jsfiddle.net/dkrestos/k5nkrrs3/) is an example (JSFiddle) that **works** with data attributes.

**Comment by vhugogarcia** [comment]
Right, it works just fine. However the listing has multiple "data-" attributes for example:
"data-name", "data-age", etc I need the search to look for all.

**Comment by vdw** [comment]
In order to accomplish that, you have to combine the contents of multiple data attributes into one data attribute.

    <li  data-merged="FirstName LastName Age Location">text to display</li>
