### ISSUE TITLE
bootstrap modal window

### ISSUE THREAD

**Issue by stupae** [vdw/HideSeek#20]
I have problem with using the plugin inside a bootstrap modal window. I guess the issue is caused by event delegation but no idea how to work around it. Please help me.

**Comment by vdw** [comment]
Hi, you have to initiate HideSeek using the "shown.bs.modal" modal event.

Here is an example of HideSeek with Bootstrap modal v3: http://jsfiddle.net/dkrestos/495z7m4v/
