### ISSUE TITLE
How to apply live search for the entire site?

### ISSUE THREAD

**Issue by VirtuaCreative** [vdw/HideSeek#28]
Hello,

Please, how should I do to apply the live search for an entire website? I mean, search for all pages and all words within the site?

Any help will be much appreciated.

Thanks for sharing your plugin with us!

**Comment by vdw** [comment]
Hi, you can use HIdeSeek on HTML list elements or similar structures (e.g.: http://vdw.github.io/HideSeek/). A search implementation for an entire site (abstract data) is out of the scope of this tool.

Thank you.
