### ISSUE TITLE
Showing div on no-result

### ISSUE THREAD

**Issue by Los799** [vdw/HideSeek#34]
There's some way to show a div or html element when there's no result? Or just apply a class by .addClass option?

Thanks

**Comment by khodakhah** [comment]
Hi, What do you mean? Where? Which file?

**Comment by Los799** [comment]
`$('#faqSearch').hideseek({
      list:             '.faqItem',
      ignore:           '.collapse'
    });`

I just want to show a div when it get no results.

**Comment by vdw** [comment]
Hi, the "_after_nodata" event is just added in order to trigger an action when there are no results. 
So, now you can do something like this:

```
$('#search').on("_after_nodata", function() {
  $('.my_custom_no_results_div').show();
});
```

Assuming there is an element like this:

```
<div class="my_custom_no_results_div" style="display:none">
  <span>No results!</span>
</div>
```

**Comment by Los799** [comment]
Awesome! Thanks!

**Comment by ecowed** [comment]
I found using the above code worked, but on researching with a found element, the no results part still displayed. I have made an incredibly hacky way around it, but would it be possible to use a callback/function as a valid entry for the nodata option? That way, someone could either specify some text to display, or their own function?
