### ISSUE TITLE
Searching include full Ul 

### ISSUE THREAD

**Issue by AdeelKhan913** [vdw/HideSeek#36]
When I search from list It shows me full ul not displaying only li record which I want to show only. Will you please guide me How I can find exact solution not other li elements. Here is my code.

` <div id="myTest">`
    `<input id="search" name="search" placeholder="Start typing here" type="text" data-list=".list">`
  `  <div class="col-md-4 list">`
       ` <div class="panel panel-primary">`
          `  <div class="panel-heading">`
          `      first panel`
           ` </div>`
          `  <div class="panel-body">`
               ` <ul>`
                 `   <li>first</li>`
           `     </ul>`
           ` </div>`
      `  </div>`

   `     <div class="panel panel-primary">`
        `    <div class="panel-heading">`
           `     Second panel`
          `  </div>`
          `  <div class="panel-body">`
            `    <ul>`
                  `  <li>second </li>`
                  `  <li>third</li>`
                   ` <li>four</li>`
             `   </ul>`
           ` </div>`
       ` </div>`
  `  </div>`
`</div>`
`</div>`

**Comment by khodakhah** [comment]
Hi,

Sorry I didn't understand what is your issued. Please explain it.

Thanks
