### ISSUE TITLE
Compatibility with table element?

### ISSUE THREAD

**Issue by jessmitch42** [vdw/HideSeek#38]
Hi there. Really love this plug-in! I'm now trying to use it now to search rows in a table based on any of the content in the row.. I'm wondering if there's a way to make this work-- not having much luck on my own. 

For example, is there a way for the search to return the second row if someone searches 5:

<table>
  <tr>
    <td>1</td>
    <td>2</td>
    <td>3</td>
  </tr>
  <tr>
    <td>4</td>
    <td>5</td>
    <td>6</td>
  </tr>
  <tr>
    <td>7</td>
    <td>8</td>
    <td>9</td>
  </tr>
</table>

I would really appreciate any suggestions or to know if it will work if the content is embedded. Thanks!

**Comment by vdw** [comment]
Hi, [here is an example](https://jsfiddle.net/dkrestos/6sfva0hg/) using a table structure.

Note: The initialization is on `tbody` tag.

**Comment by jessmitch42** [comment]
Fantastic! Thanks so much for this. Works for me :)

**Comment by goeroe** [comment]
Example doesn't seem to work anymore?

**Comment by shafali03** [comment]
Hi I wanted to ask can I use this plugin for live search on image gallery

**Comment by vdw** [comment]
@goeroe Example works again.
@shafali03 You can use HideSeek to search on any elements, even images as long as you use the `attribute` option.

**Comment by shafali03** [comment]
thanks for letting me know

**Comment by JustinWarren** [comment]
Hello!  I am trying to use your plugin while working on a gallery.  I need help in knowing how to have the pics show up when I type a title (ex-  "Mountains" and then mountain pictures show up).  Any help would be greatly appreciated!  Thanks!

**Comment by vdw** [comment]
@JustinWarren,  you can use HideSeek to search on any elements, even images as long as you use the `attribute` option.

Here is an [example](https://jsfiddle.net/dkrestos/8Ldkb1qd/) (just replace anchor elements with image elements and fill the data attributes `keywords` with some keywords).

**Comment by neerbappoo** [comment]
For the table structure, when you select all value from the input field and hit the delete button, the table does not reset
