### ISSUE TITLE
Highlight v4 conflicts with other jQuery plugins running highlight v5

### ISSUE THREAD

**Issue by YPCrumble** [vdw/HideSeek#39]
First, thanks for building an awesome library!

The `removeHighlight` function in highlight v4 conflicts with the same function in the v5 library. I'm using [Selectize](https://github.com/selectize/selectize.js) in a different part of my site and it uses v5, which uses `span.highlight` rather than `mark.highlight` to add/remove the highlights. This means that we can't use HideSeek with any plugins that use the updated highlight library.

I would suggest either updating the highlight library within HideSeek to v5 or removing it from the repo and listing highlight as a dependency. I'm happy to create a PR for either or another solution if there's a better one?

EDIT - looking deeper it looks like Selectize has edited their `removeHighlight` function from the v5 original so I'll probably resolve this by forking this repo and renaming the `removeHighlight` function to something else.

**Comment by coryhake** [comment]
Added a pull request to update Highlight to v5, feel free to fork if you haven't solved this on your own yet.
