### ISSUE TITLE
Specify class (or set of classes) as attribute

### ISSUE THREAD

**Issue by brettmhoffman** [vdw/HideSeek#6]
It would be very handy to be able to set a specific tag or class name as the "attribute" to search against.

**Comment by vdw** [comment]
By default, the results are based on the text inside the list elements, but, you can change this by setting the attribute you want with the option "[attribute](https://github.com/vdw/HideSeek/wiki/Options#user-content-attribute-option)". E.g. If you have a list of logo images (for example a list of brands) you can set the option "[attribute](https://github.com/vdw/HideSeek/wiki/Options#user-content-attribute-option)" to "alt".
