### ISSUE TITLE
Hideseek function is not defined

### ISSUE THREAD

**Issue by Kellenkjames** [vdw/HideSeek#62]
For some reason my console keeps reading - hideseek function is not defined when trying to call the function. I have downloaded the latest version of jQuery (3.3.1) and I'm using v0.8.0 for the jquery.hideseerk.min.js file. Have been debugging this for days and cannot find out what's causing the error. Please help!

Here is a link to my repo :) 

https://github.com/Kellenkjames/Interactive-Photo-Gallery

**Comment by Sakthi002** [comment]
i am also facing the same issue.. what is the solution for this
