### ISSUE TITLE
How to set up jQuery for multi forms on the page?

### ISSUE THREAD

**Issue by adulfan** [vdw/HideSeek#7]
I have couple search form on the page. How do I run the search per form, initialising all the hideseek at once? Or do I have to do it per form? Thank you.

**Comment by vdw** [comment]
You can initialize the plugin per form using the data attribute "toggle" avoiding to write any javascript:

e.g. 
```html
<input type="text" data-toggle="hideseek" data-list=".list">
```

Where .list is the class or id of the list you want the input to control, 
so you can have multiple lists like this:

e.g.
```html
<input type="text" data-toggle="hideseek" data-list=".list_1">
<input type="text" data-toggle="hideseek" data-list=".list_2">
<input type="text" data-toggle="hideseek" data-list=".list_2">
```

**Comment by adulfan** [comment]
Dmitris, thank you, I got it by changing the class for each list. Still not sure how, but it works :) Wonderfull light plugin. I was wondering if I am building something else but using your lug in can I distribute my code?

Sincerely,
Anna Dulfan
Senior Consultant

NORTHPOINTDigital
130 W 42nd Street, suite 505
New York, NY 10036
Phone: 212.819.1700
 <mailto:adulfan@northpointdigital.com>adulfan@northpointdigital.com <mailto:adulfan@northpointdigital.com> | http://northpointdigital.com <http://northpointdigital.com/>
_________________________________







> On Apr 5, 2015, at 1:35 PM, Dimitris Krestos <notifications@github.com> wrote:
> 
> You can initialize the plugin per form using the data attribute "toggle" avoiding to write any javascript:
> 
> e.g.
> 
> <input type="text" data-toggle="hideseek" data-list=".list">
> Where .list is the class or id of the list you want the input to control, 
> so you can have multiple lists like this:
> 
> e.g.
> 
> <input type="text" data-toggle="hideseek" data-list=".list_1">
> <input type="text" data-toggle="hideseek" data-list=".list_2">
> <input type="text" data-toggle="hideseek" data-list=".list_2">
> —
> Reply to this email directly or view it on GitHub <https://github.com/vdw/HideSeek/issues/7#issuecomment-89816696>.
> 


-- 



------------------------------
 
Confidentiality and Security Notice: This e-mail, including any 
attachments, may contain confidential and proprietary information and may 
be legally privileged or otherwise protected by law. It may be read and 
used solely by the intended recipient(s), and any review, use or 
distribution by others is strictly prohibited. If you are not an intended 
recipient, please notify us immediately by replying to the sender and 
delete this e-mail, including any attachments, from your system immediately 
without reading, copying or distributing them. Thank you for your 
cooperation.
